# Generated by Django 2.2.13 on 2023-03-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minicom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmodel',
            name='engaged_by',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='team',
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='in_conversation_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minicom.CompanyModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='is_author',
            field=models.BooleanField(default=False, help_text='user setup organzation'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='domain',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='minicom.ConversationModel'),
        ),
    ]
