# Generated by Django 2.2.13 on 2023-03-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minicom', '0002_auto_20230308_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmodel',
            name='customer_country_iso',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='locale',
        ),
    ]
